version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/dist:/usr/share/nginx/html

  node:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./react:/src
    working_dir: /src
    tty: true